"""Update session table

Revision ID: 5da6f0b2f6b7
Revises: 83c6135cf092
Create Date: 2024-08-07 08:31:09.405914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da6f0b2f6b7'
down_revision: Union[str, None] = '83c6135cf092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('player1_ready', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('session', sa.Column('player2_ready', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'player2_ready')
    op.drop_column('session', 'player1_ready')
    # ### end Alembic commands ###
