version: "3.8"

services:
  api:
    container_name: api
    build:
      context: docker/api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${API_PORT}:8000
    volumes:
      - ./app/api:/app/api
      - ./app/migrations:/app/migrations
      - ./app/alembic.ini:/app/alembic.ini
    env_file:
      - .env
    command: ["/usr/local/bin/entrypoint.sh"]

  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
